// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 审计日志统计摘要
 */
export type AuditSummary = { total_processing_audits: number, total_execution_logs: number, total_tokens: number, total_cost: number, success_rate: number, };
