// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 处理审计日志查询过滤器
 */
export type AuditQueryFilter = { 
/**
 * 按 step 过滤（Classifier, Extract, Upgrade, Review 等）
 */
step: string | null, 
/**
 * 按 trace_id 过滤
 */
trace_id: string | null, 
/**
 * 起始时间（ISO 8601 格式）
 */
since: string | null, 
/**
 * 结束时间（ISO 8601 格式）
 */
until: string | null, 
/**
 * 返回条数限制，默认 100，最大 500
 */
limit: number, };
