// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 执行日志行（前端 DTO）
 */
export type ExecutionLogRow = { id: string, task_id: string, task_name: string, status: string, started_at: string, finished_at: string, duration_ms: number, output: string | null, error: string | null, created_at: string, };
