// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 执行日志查询过滤器
 */
export type ExecutionLogFilter = { 
/**
 * 按 task_id 过滤
 */
task_id: string | null, 
/**
 * 按 status 过滤（Success, Failed, Skipped, Timeout）
 */
status: string | null, 
/**
 * 返回条数限制，默认 100，最大 500
 */
limit: number, };
