// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 处理审计日志行（前端 DTO）
 */
export type ProcessingAuditRow = { event_id: string, record_id: string | null, trace_id: string, step: string, timestamp: string, duration_ms: number, model: string, model_version: string, prompt_id: string, 
/**
 * prompt 参数（JSON 字符串）
 */
prompt_params: string, input_summary: string, 
/**
 * 输出结果（JSON 字符串）
 */
output: string, confidence: number, token_input: number, token_output: number, cost_estimate: number, upgrade_reason: string | null, previous_model: string | null, review_verdict: string | null, 
/**
 * 审核问题（JSON 数组字符串）
 */
review_issues: string | null, user_action: string | null, user_correction: string | null, };
