// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { Confidence } from "./Confidence";
import type { EventType } from "./EventType";
import type { JsonValue } from "./serde_json/JsonValue";
import type { Source } from "./Source";

/**
 * 事件 —— 系统的原子单位，不可变
 */
export type Event = { id: string, timestamp: string, collected_at: string, source: Source, source_confidence: Confidence, type: EventType, content: JsonValue, raw_payload: string, tags: Array<string>, related_ids: Array<string>, attachments: Array<Attachment>, };
