// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 事件类型
 */
export type EventType = "Message" | "DocumentChange" | "TaskUpdate" | "Meeting" | "CalendarEvent" | "Email" | "Approval" | "OkrUpdate" | "Browsing" | "AppActivity" | "ManualNote";
