// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 审核问题
 */
export type Issue = { 
/**
 * 问题类型：missing_field, invalid_state, format_error, low_confidence 等
 */
issue_type: string, 
/**
 * 严重程度：critical, high, medium, low
 */
severity: string, 
/**
 * 问题描述
 */
description: string, 
/**
 * 修复建议
 */
suggestion: string, };
