// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 审核结论
 */
export type ReviewVerdict = "Approved" | { "NeedsFix": string } | { "NeedsReview": string };
