// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./Issue";
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * 审核结果
 */
export type ReviewResult = { verdict: ReviewVerdict, issues: Array<Issue>, 
/**
 * 审核者：rule, small_model, large_model
 */
reviewer: string, confidence: number, };
