// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";
import type { TaskStatus } from "./TaskStatus";

/**
 * 任务
 */
export type Task = { id: string, created_at: string, updated_at: string, title: string, description: string, status: TaskStatus, priority: Priority, due_date: string | null, completed_at: string | null, project: string | null, parent_task: string | null, assignee: string, collaborators: Array<string>, source_event_ids: Array<string>, source_platform: string, feishu_task_id: string | null, ai_summary: string | null, ai_progress: string | null, ai_risk: string | null, tags: Array<string>, confidence: number, needs_review: boolean, obsidian_path: string, };
