// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * 工作记录 —— 处理层的输出
 */
export type WorkRecord = { id: string, created_at: string, source_event_ids: Array<string>, title: string, summary: string, detail: string, category: Category, project: string | null, people: Array<string>, tags: Array<string>, task_status: string | null, task_due: string | null, task_priority: string | null, task_progress: string | null, model_used: string, confidence: number, needs_review: boolean, obsidian_path: string, };
